### ISSUE TITLE
Build failure on OS X: 'gmp.h' file not found

### ISSUE THREAD

**Issue by oyamad** [blegat/CDDLib.jl#5]
I have a problem similar to but different from #2 and #4.
The output is [here](http://nbviewer.jupyter.org/gist/oyamad/e2d0404a2c56703ac78f8f31cdf9d957/build_CDDLib.ipynb).

* configure says

  ```
  checking gmp.h usability... no
  checking gmp.h presence... no
  ```

  but `gmp.h` exists in `$HOME/.julia/v0.5/Homebrew/deps/usr/Cellar/gmp/6.1.1/include`.

* `$HOME/.julia/v0.5/CDDLib/deps/usr` does not exists.

* I don't have Homebrew (not Homebrew.jl) installed in this machine. Build succeeded in my other machine with Homebrew installed.

How can I tell `cdd` the location of `gmp.h`?

**Comment by oyamad** [comment]
I somehow figured out how to pass the information about include and lib files when building.
See https://github.com/oyamad/CDDLib.jl/commit/32560211b58e4a8d52996d0b9748ba9fc15dddd1 and https://github.com/oyamad/CDDLib.jl/commit/6abb05411b50e872e75b6d492b432ad598047287.

**Comment by blegat** [comment]
Hey, sorry for replying so late, I was travelling. Thanks a lot for figuring this out ! Mac OS always worked out of the box in travis without Homebrew so I couldn't test if my homebrew code was actually working.
Normally the only tricky thing to get is `gmp.h` since I can use the Julia GMP library.
In your case, it didn't work without adding `lib_dirs = libdirs` in the `BuildProcess` ?

**Comment by oyamad** [comment]
No, it doesn't work without it (i.e., without the second commit https://github.com/oyamad/CDDLib.jl/commit/6abb05411b50e872e75b6d492b432ad598047287).

[Here](http://nbviewer.jupyter.org/gist/oyamad/e2d0404a2c56703ac78f8f31cdf9d957/build_CDDLib_2.ipynb)'s the output of build with the first commit https://github.com/oyamad/CDDLib.jl/commit/32560211b58e4a8d52996d0b9748ba9fc15dddd1 only. The errors are the same as those in #4.

Ideally, `$HOME/.julia/v0.5/Homebrew/deps/usr/lib` should be symlinked to `$HOME/.julia/v0.5/CDDLib/deps/usr`. Is there any way to do this during the build process?

**Comment by blegat** [comment]
Ok thanks a lot. Can you make a pull request with your changes ?
